const ASSISTANT_STREAM_START_CHANNEL = "assistant:stream:start";
const ASSISTANT_STREAM_CHUNK_CHANNEL = "assistant:stream:chunk";
const ASSISTANT_STREAM_DONE_CHANNEL = "assistant:stream:done";
const ASSISTANT_STREAM_ERROR_CHANNEL = "assistant:stream:error";

module.exports = {
  ASSISTANT_STREAM_START_CHANNEL,
  ASSISTANT_STREAM_CHUNK_CHANNEL,
  ASSISTANT_STREAM_DONE_CHANNEL,
  ASSISTANT_STREAM_ERROR_CHANNEL,
};
