const ASSISTANT_STREAM_START_CHANNEL = "assistant:stream:start";
const ASSISTANT_STREAM_CHUNK_CHANNEL = "assistant:stream:chunk";
const ASSISTANT_STREAM_DONE_CHANNEL = "assistant:stream:done";
const ASSISTANT_STREAM_ERROR_CHANNEL = "assistant:stream:error";
const ASSISTANT_CONVERSATION_CREATE_CHANNEL = "assistant:conversation:create";
const ASSISTANT_CONVERSATION_LIST_CHANNEL = "assistant:conversation:list";
const ASSISTANT_CONVERSATION_MESSAGES_CHANNEL = "assistant:conversation:messages";
const ASSISTANT_SETTINGS_GET_CHANNEL = "assistant:settings:get";
const ASSISTANT_SETTINGS_SET_CHANNEL = "assistant:settings:set";

module.exports = {
  ASSISTANT_STREAM_START_CHANNEL,
  ASSISTANT_STREAM_CHUNK_CHANNEL,
  ASSISTANT_STREAM_DONE_CHANNEL,
  ASSISTANT_STREAM_ERROR_CHANNEL,
  ASSISTANT_CONVERSATION_CREATE_CHANNEL,
  ASSISTANT_CONVERSATION_LIST_CHANNEL,
  ASSISTANT_CONVERSATION_MESSAGES_CHANNEL,
  ASSISTANT_SETTINGS_GET_CHANNEL,
  ASSISTANT_SETTINGS_SET_CHANNEL,
};
