const ASSISTANT_STREAM_START_CHANNEL = "assistant:stream:start";
const ASSISTANT_STREAM_CHUNK_CHANNEL = "assistant:stream:chunk";
const ASSISTANT_STREAM_REASONING_CHANNEL = "assistant:stream:reasoning";
const ASSISTANT_STREAM_STATUS_CHANNEL = "assistant:stream:status";
const ASSISTANT_STREAM_TOOL_CHANNEL = "assistant:stream:tool";
const ASSISTANT_STREAM_ABORT_CHANNEL = "assistant:stream:abort";
const ASSISTANT_STREAM_DONE_CHANNEL = "assistant:stream:done";
const ASSISTANT_STREAM_ERROR_CHANNEL = "assistant:stream:error";
const ASSISTANT_CONVERSATION_CREATE_CHANNEL = "assistant:conversation:create";
const ASSISTANT_CONVERSATION_LIST_CHANNEL = "assistant:conversation:list";
const ASSISTANT_CONVERSATION_MESSAGES_CHANNEL = "assistant:conversation:messages";
const ASSISTANT_CONVERSATION_TIMELINE_CHANNEL = "assistant:conversation:timeline";
const ASSISTANT_CONVERSATION_DELETE_CHANNEL = "assistant:conversation:delete";
const ASSISTANT_CONVERSATION_REPLACE_MESSAGES_CHANNEL = "assistant:conversation:replace-messages";
const ASSISTANT_SETTINGS_GET_CHANNEL = "assistant:settings:get";
const ASSISTANT_SETTINGS_SET_CHANNEL = "assistant:settings:set";
const ASSISTANT_MCP_LIST_TOOLS_CHANNEL = "assistant:mcp:list-tools";
const ASSISTANT_MCP_CALL_TOOL_CHANNEL = "assistant:mcp:call-tool";

export {
  ASSISTANT_STREAM_START_CHANNEL,
  ASSISTANT_STREAM_CHUNK_CHANNEL,
  ASSISTANT_STREAM_REASONING_CHANNEL,
  ASSISTANT_STREAM_STATUS_CHANNEL,
  ASSISTANT_STREAM_TOOL_CHANNEL,
  ASSISTANT_STREAM_ABORT_CHANNEL,
  ASSISTANT_STREAM_DONE_CHANNEL,
  ASSISTANT_STREAM_ERROR_CHANNEL,
  ASSISTANT_CONVERSATION_CREATE_CHANNEL,
  ASSISTANT_CONVERSATION_LIST_CHANNEL,
  ASSISTANT_CONVERSATION_MESSAGES_CHANNEL,
  ASSISTANT_CONVERSATION_TIMELINE_CHANNEL,
  ASSISTANT_CONVERSATION_DELETE_CHANNEL,
  ASSISTANT_CONVERSATION_REPLACE_MESSAGES_CHANNEL,
  ASSISTANT_SETTINGS_GET_CHANNEL,
  ASSISTANT_SETTINGS_SET_CHANNEL,
  ASSISTANT_MCP_LIST_TOOLS_CHANNEL,
  ASSISTANT_MCP_CALL_TOOL_CHANNEL,
};
